#!/bin/bash

# Variables
acc=$1
repo=$2
path=$3
def="davipuddo"

# Check parameters

if [ $# == 0 ]; then
	echo "ERROR: No repository name was given!"
	echo "To clone a repository first give the owner's name, then give the repository name."

elif [ $# -gt 3 ]; then
	echo "ERROR: Too many parameters were given!"

else
	line="https://github.com/"
	if [ $# == 1 ]; then 	# If only one parameter is given use the default username
		repo=$acc
		line="$line$def/$repo.git"
	elif [ $# == 2 ]; then
		line="$line$acc/$repo.git"
	else
		if [ "$acc" == "-d" ]; then
			line="$line$def/$repo.git $path"
		else
			line="$line$acc/$repo.git $path"
		fi
	fi
	
	git clone $line			# Clone repository
fi
