#!/bin/bash

readDelete()
{
	echo "Delete:"
	ls *.class
	ls ./*/*.class
	echo "[y/n]"

	read x
	if [ $x == "y" ]; then
		rm *.class
		rm ./*/*.class
		echo "The files were deleted."
	elif [ $x == "n" ]; then
		echo "Aborting script."
	else
		echo "ERROR: Invalid input!"
		echo ""
		readDelete
	fi
}

f=(*.class)

if [ -f "${f[0]}" ]; then
	readDelete
else 
	echo "ERROR: No file '.class' was found!"
fi
