#!/bin/bash

export PGHOST=trackle.postgres.database.azure.com
export PGUSER=tadm
export PGPORT=5432
export PGDATABASE=trackle
export PGPASSWORD="T39rackle!"

if [ $# == 1 ]; then
		psql <"$1"

elif [ $# == 0 ]; then
	psql

fi
